package com.statsig.sdk

object Const {
    const val EMPTY_STR: String = ""
    const val ZERO: String = "0"

    const val GT: String = "gt"
    const val GTE: String = "gte"
    const val LT: String = "lt"
    const val LTE: String = "lte"
    const val VERSION_GT: String = "version_gt"
    const val VERSION_GTE: String = "version_gte"
    const val VERSION_LT: String = "version_lt"
    const val VERSION_LTE: String = "version_lte"
    const val VERSION_EQ: String = "version_eq"
    const val VERSION_NEQ: String = "version_neq"
    const val ANY: String = "any"
    const val ANY_CASE_SENSITIVE: String = "any_case_sensitive"
    const val NONE_CASE_SENSITIVE: String = "none_case_sensitive"
    const val STR_STARTS_WITH_ANY: String = "str_starts_with_any"
    const val STR_ENDS_WITH_ANY: String = "str_ends_with_any"
    const val STR_CONTAINS_ANY: String = "str_contains_any"
    const val STR_CONTAINS_NONE: String = "str_contains_none"
    const val STR_MATCHES: String = "str_matches"
    const val EQ: String = "eq"
    const val NEQ: String = "neq"
    const val BEFORE: String = "before"
    const val AFTER: String = "after"
    const val ON: String = "on"
    const val IN_SEGMENT_LIST: String = "in_segment_list"
    const val NOT_IN_SEGMENT_LIST: String = "not_in_segment_list"

    const val APP_VERSION: String = "app_version"
    const val APPVERSION: String = "appversion"
    const val BROWSER_NAME: String = "browser_name"
    const val BROWSER_VERSION: String = "browser_version"
    const val BROWSERNAME: String = "browsername"
    const val BROWSERVERSION: String = "browserversion"
    const val CML_SHA_256: String = "SHA-256"
    const val COUNTRY: String = "country"
    const val DEFAULT: String = "default"
    const val DISABLED: String = "disabled"
    const val EMAIL: String = "email"
    const val IP: String = "ip"
    const val IPADDRESS: String = "ipaddress"
    const val IP_ADDRESS: String = "ip_address"
    const val LOCALE: String = "locale"
    const val NONE: String = "none"
    const val OS_NAME: String = "os_name"
    const val OS_VERSION: String = "os_version"
    const val OSNAME: String = "osname"
    const val OSVERSION: String = "osversion"
    const val USER_AGENT: String = "user_agent"
    const val USER_ID: String = "user_id"
    const val USERAGENT: String = "useragent"
    const val USERID: String = "userid"

    const val PUBLIC: String = "public"
    const val FAIL_GATE: String = "fail_gate"
    const val PASS_GATE: String = "pass_gate"
    const val IP_BASED: String = "ip_based"
    const val UA_BASED: String = "ua_based"
    const val USER_FIELD: String = "user_field"
    const val CURRENT_TIME: String = "current_time"
    const val ENVIRONMENT_FIELD: String = "environment_field"
    const val USER_BUCKET: String = "user_bucket"
    const val UNIT_ID: String = "unit_id"
}
